amran15/instant-offer

.gitignore
package-lock.json
package.json
server/modules/pool.js
src/components/App/App.js
src/components/Signature/Signature.js

finished the signature feature component.
approve the merge please

signature component to the project repo

---

package-lock.json
package.json
src/components/App/App.js
src/components/Documents/Documents.css
src/components/Documents/Documents.js
src/components/Drafts/Drafts.js
src/components/Footer/Footer.css
src/components/Footer/Footer.js
src/components/Nav/Nav.css
src/components/Nav/Nav.js

I created a navbar to use for the time-being.

navbar created

---

database.sql
server/routes/listing_contract.router.js
server/routes/purchase_agreement.router.js
server/server.js

I created two routers for our listing and purchase routes and also I changed the name of the purchase_contract to purchase_agreement to reflect our wireframes

routes created for listing and purchase routers

---

server/modules/pool.js
server/routes/purchase_agreement.router.js

I created a simple get router for purchase_agreement

Get router

---

server/routes/listing_contract.router.js

add const rejectUnauthenticated to listing contract router

Listing contract route

---

src/components/ListingContract/ListingContract.js
src/components/PurchaseAgreement/PurchaseAgreement.js

added list of categories for each form

questions categories for listing and purchase

---

src/components/ListingDrafts/ListingDrafts.js
src/components/ListingDraftsIndividualDocs/ListingDraftsIndividualDocs.js

i split the listing contact draft compenent into two components. there is now a ListingDraftsIndividualDocs componenet. Here, Matt can go ahead and add logic.

split listing contract draft into two componenents

---

src/components/App/App.js
src/components/Footer/Footer.css
src/components/Footer/Footer.js
src/components/ListingContract/ListingContract.js
src/components/PurchaseAgreement/PurchaseAgreement.js

I also need to fix that button after this footer

commented out footer, we can decide to bring that in later if we want

---

src/components/App/App.js
src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory4.js
src/components/ListingContract/ListingCategory5.js
src/components/ListingContract/ListingCategory6.js
src/components/ListingContract/ListingCategory7.js
src/components/ListingContract/ListingCategory8.js
src/components/ListingContract/ListingContract.js

hey pushing the pages up. they are all linking together.

finished linking listing pages

---

src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/PurchaseAgreement/PurchaseAgreement.js

completed listing questions category 1. check it out

listing questions page one completed

---

src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory3.js

hey ladies, please review the code.

completed category2 and category3 questions

---

src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory4.js

completed the fourth category. check and approve please.

listing category 4 completed

---

src/components/ListingContract/ListingCategory8.js
src/components/ListingContract/ListingContract8.css

hardcoded questions for listing Contract 8 page, will need to go back to touchup question formatting and buttons.

Listing contract8

---

src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory4.js
src/components/ListingContract/ListingCategory5.js

please take a look at 5 and approve

category 5 halfway completed

---

src/components/PurchaseAgreementQuestions/PurchaseCategory3.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js

questions for page 3. need to fix buttons

purchase category page 3

---

src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory4.js
src/components/ListingContract/ListingCategory8.js

Buttons functional

---

src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory4.js
src/components/ListingContract/ListingCategory5.js
src/components/ListingContract/ListingCategory6.js
src/components/ListingContract/ListingCategory7.js
src/components/ListingContract/ListingCategory8.css

Completed questions for category 5, still need to work on 6 and 7

Questions5 6 7

---

server/routes/listing_contract.router.js
src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory4.js
src/components/ListingContract/ListingCategory5.js
src/components/ListingContract/ListingCategory8.js
src/redux/reducers/index.js
src/redux/reducers/listingcategory8reducer.js
src/redux/sagas/index.js
src/redux/sagas/listingcategory8saga.js

listing category 8 logic from front end to sagas and router works

---

src/components/App/App.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js
src/components/PurchaseAgreementQuestions/PurchaseCategory5.js
src/components/PurchaseAgreementQuestions/PurchaseCategory9.js

we forget to add another category for purchase agreement

add purchase category 9 for purchase agreement

---

server/routes/listing_contract.router.js
server/routes/purchase_agreement.router.js
src/components/ListingContract/ListingCategory4.js

created delete routes for both listing and purchase

created delete routes

---

server/routes/listing_contract.router.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory4.js
src/components/ListingContract/ListingCategory5.js
src/components/ListingContract/ListingCategory8.js
src/redux/reducers/index.js
src/redux/reducers/listingcategory3Reducer.js
src/redux/reducers/listingcategory4Reducer.js
src/redux/reducers/listingcategory5Reducer.js
src/redux/sagas/index.js
src/redux/sagas/listingcategory3saga.js
src/redux/sagas/listingcategory4saga.js
src/redux/sagas/listingcategory5saga.js
src/redux/sagas/listingcategory8saga.js

hey people....latest code . review, and approve please

logic for categories from front to server need to send data to database

---

server/routes/listing_contract.router.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory6.js
src/components/ListingContract/ListingCategory7.js
src/components/ListingContract/ListingCategory8.js
src/redux/reducers/index.js
src/redux/reducers/listingcategory6Reducer.js
src/redux/reducers/listingcategory7Reducer.js
src/redux/sagas/index.js
src/redux/sagas/listingcategory6saga.js
src/redux/sagas/listingcategory7saga.js

new pull request...review and approve please

completed all listing states and logic

---

src/components/App/App.js
src/components/ListingContract/ListingCategory1.js
src/components/ListingContract/ListingCategory2.js
src/components/ListingContract/ListingCategory3.js
src/components/ListingContract/ListingCategory4.js
src/components/ListingContract/ListingCategory5.js
src/components/ListingContract/ListingCategory6.js
src/components/ListingContract/ListingCategory7.js
src/components/ListingContract/ListingCategory8.js
src/components/ListingContract/ListingContract.js
src/components/ListingReview/ListingReview.js

added next buttons to listing

---

src/components/PurchaseAgreement/PurchaseAgreement.css
src/components/PurchaseAgreement/PurchaseAgreement.js
src/components/PurchaseAgreementQuestions/PurchaseCategory1.js
src/components/PurchaseAgreementQuestions/PurchaseCategory2.js
src/components/PurchaseAgreementQuestions/PurchaseCategory3.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js
src/components/PurchaseAgreementQuestions/PurchaseCategory5.js
src/components/PurchaseAgreementQuestions/PurchaseCategory6.js
src/components/PurchaseAgreementQuestions/PurchaseCategory7.js
src/components/PurchaseAgreementQuestions/PurchaseCategory8.js
src/components/PurchaseAgreementQuestions/PurchaseCategory9.js

build out all the questions pages for Purchase Agreement

Purchase questions

---

src/components/ListingContractButton/ListingContractButton.js
src/components/Nav/Nav.css
src/components/PurchaseAgreementButton/PurchaseAgreementButton.css
src/components/PurchaseAgreementButton/PurchaseAgreementButton.js

fixed drawer so words don't disappear on when hovering mouse over them. alos changed color of drawer.

fixed drawer.

---

src/redux/sagas/index.js

fixed sagas conflict - please approve

fixed sagas conflict

---

src/components/ListingContractQuestions/ListingCategory1.js
src/components/ListingContractQuestions/ListingCategory2.js
src/redux/reducers/purchaseAgreementReducer1.js
src/redux/reducers/purchaseAgreementReducer2.js

new logic to listing 1 and 2

---

src/components/App/App.js
src/components/PurchaseAgreementQuestions/PurchaseCategory6.js

Purchase7logic

---

public/index.html
server/routes/listing_contract.router.js
src/components/App/App.css
src/components/PurchaseAgreementQuestions/PurchaseCategory5.js
src/components/Signature/Signature.js
src/redux/sagas/signSaga.js

have signature working and saving

---

server/routes/listing_contract.router.js
src/components/ListingContractQuestions/ListingCategory7.js

working on finishing the put request on listing pages 7/8

working on put-Saga7/8

---

src/components/ListingContractQuestions/ListingCategory1.js

fixed questions for listing page 1

---

src/components/App/App.css

Login background

---

server/routes/listing_contract.router.js
src/components/Signature/Signature.js
src/components/SignedDocs/SignedDocs.js
src/redux/sagas/index.js
src/redux/sagas/signSaga.js

Saving categories

---

src/components/ListingContractQuestions/ListingCategory1.js
src/components/ListingContractQuestions/ListingCategory2.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory4.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory8.js
src/redux/sagas/putAnswers.js

I did pages 1-8 local state, I still need to revisit the checkboxes because it comes up as null in some entries

Put saga pages1 4

---

server/routes/listing_contract.router.js
src/components/InfoPage/InfoPage.js
src/components/ListingContractSignedIndividualDocs/ListingContractSignedIndividualDocs.js
src/components/Signature/Signature.js
src/components/SignedDocs/SignedDocs.js
src/redux/sagas/pdfListing.js

pdf and and signature aligned

---

src/components/ListingContractQuestions/ListingCategory1.js
src/components/ListingContractQuestions/ListingCategory2.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory4.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory7.js
src/components/Signature/Signature.js

changes made for L3 and L73

---

src/components/App/App.css
src/components/Signature/Signature.js

updating the app

---

src/components/ListingContractQuestions/ListingCategory1.js
src/components/ListingContractQuestions/ListingCategory5.js

Fix purchase post saga/reducer/route

Fix purchase post saga/reducer/route

---

src/components/ListingContractQuestions/ListingCategory1.js

added today's date

---

src/components/ListingContractQuestions/ListingCategory1.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory4.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory8.js
src/redux/sagas/pdfListing.js

fixed the nulls and consent typeo

Feature testing

---

src/redux/sagas/pdfListing.js

i am sure it is the best one now

signature is lined up

---

src/redux/sagas/pdfListing.js

double checking categories

---

src/components/ListingContractQuestions/ListingCategory8.js

removed labels from seller's information

removed labels from seller's information

---

src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory6.js

pages 3/4/5/6 checkboxes logic works

Checkout logic

---

server/routes/listing_contract.router.js
src/components/ListingContractSignedIndividualDocs/ListingContractSignedIndividualDocs.js
src/redux/reducers/index.js
src/redux/reducers/listingSignedDocsReducer.js
src/redux/sagas/fetchListingSignedDocs.js
src/redux/sagas/index.js

Mapping signed listing contracts --

Mapping signed listing contracts

---

server/routes/purchase_agreement.router.js
src/components/ListingDraftsIndividualDocs/ListingDraftsIndividualDocs.js
src/components/PurchaseAgreementDraftsIndividualDocs/PurchaseAgreementDraftsIndividualDocs.js
src/components/PurchaseAgreementSignedIndividualDocs/PurchaseAgreementSignedIndividualDocs.js

post Router works

---

src/components/ListingContractButton/ListingContractButton.js
src/components/ListingContractQuestions/ListingCategory2.js
src/components/PurchaseAgreementButton/PurchaseAgreementButton.js
src/redux/reducers/createNewPurchaseFormReducer.js
src/redux/reducers/index.js
src/redux/sagas/index.js
src/redux/sagas/newPurchaseAgreementForm.js

checkbox logic is done for all 8 pages

checkbox logic is done for all 8 pages

---

src/components/ListingContractQuestions/ListingCategory2.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory7.js
src/components/ListingContractQuestions/ListingCategory8.js

Logic to keep listing info

---

public/index.html
src/components/App/App.css
src/components/PurchaseAgreementQuestions/PurchaseCategory1.js
src/components/Signature/Signature.js
src/redux/reducers/index.js
src/redux/sagas/index.js

i tinkered with the signature bug

Fixingcheckboxes

---

database.sql
src/components/ListingContractQuestions/ListingCategory2.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory4.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory7.js
src/components/ListingContractQuestions/ListingCategory8.js

back buttons go back to /ListingContract page

back buttons

---

src/redux/sagas/pdfListing.js

fixed signature coordinants for all pages

---

src/redux/sagas/pdfListing.js

fixed date placements on listing pdfs

---

server/routes/listing_contract.router.js
src/components/App/App.js
src/components/ListingContractButton/ListingContractButton.js
src/components/ListingContractQuestions/ListingCategory1.js
src/redux/reducers/index.js
src/redux/reducers/setListingAnswersReducer.js
src/redux/sagas/fetchListingAnswers.js

the response.id shows up as undefined.

Get answers by

---

src/components/App/App.js
src/components/PurchaseAgreement/PurchaseAgreement.js
src/components/PurchaseAgreementQuestions/PurchaseCategory1.js
src/components/Signature/PurchaseSignature.js

finished the purchase signature

purchase signature component added

---

src/components/InfoPage/InfoPage.js
src/redux/sagas/pdfOffer.js

I added the logic for pages 1 through 6

Feature pdf offer

---

src/redux/sagas/pdfOffer.js

Ready to start working on coordinates.

pages 1 through 13 complate

---

src/components/ListingContractQuestions/ListingCategory1.js
src/components/ListingContractQuestions/ListingCategory2.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory4.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory7.js
src/components/ListingContractQuestions/ListingCategory8.js
src/components/PurchaseAgreementQuestions/PurchaseCategory1.js
src/redux/sagas/fetchListingAnswers.js
src/redux/sagas/index.js

cleaned up all those unexpected character ''

cleaned up all those unexpected character

---

src/components/ListingContractQuestions/ListingCategory2.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory4.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory7.js
src/components/ListingContractQuestions/ListingCategory8.js

redirects user to previous page with info still on the page

Back button listing

---

src/components/PurchaseAgreementQuestions/PurchaseCategory2.js
src/components/PurchaseAgreementQuestions/PurchaseCategory3.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js
src/components/PurchaseAgreementQuestions/PurchaseCategory5.js
src/components/PurchaseAgreementQuestions/PurchaseCategory6.js
src/components/PurchaseAgreementQuestions/PurchaseCategory7.js

Purchase5-7 answers (still need to complete 8 and 9)

Purchase5-9 answers

---

src/components/PurchaseAgreementQuestions/PurchaseCategory6.js
src/components/PurchaseAgreementQuestions/PurchaseCategory7.js
src/components/PurchaseAgreementQuestions/PurchaseCategory8.js
src/components/PurchaseAgreementQuestions/PurchaseCategory9.js
src/redux/sagas/fetchPurchaseAnswers.js

Purchase local state --old logic, will work on transferring logic from listing now

Purchase local state

---

src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory7.js
src/components/ListingContractQuestions/ListingCategory8.js

completed autofill for all listing

---

src/components/PurchaseAgreementQuestions/PurchaseCategory1.js
src/components/PurchaseAgreementQuestions/PurchaseCategory2.js
src/components/PurchaseAgreementQuestions/PurchaseCategory3.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js
src/components/PurchaseAgreementQuestions/PurchaseCategory5.js
src/components/PurchaseAgreementQuestions/PurchaseCategory6.js
src/components/PurchaseAgreementQuestions/PurchaseCategory7.js
src/components/PurchaseAgreementQuestions/PurchaseCategory8.js
src/components/PurchaseAgreementQuestions/PurchaseCategory9.js
src/redux/sagas/index.js
src/redux/sagas/putAnswersOffer.js
src/redux/sagas/putPurchaseAnswers.js

Purchase local state logic

---

src/redux/sagas/pdfListing.js

pdf font size fixed

---

src/components/App/App.js
src/components/Signature/PurchaseSignature.js
src/components/Signature/Signature.js

fix purchase sign

---

src/components/InfoPage/InfoPage.js
src/redux/sagas/pdfListing.js
src/redux/sagas/pdfOffer.js

check and approve this pull request please

pdf purchase 2 completed

---

src/components/ListingContract/ListingContract.js
src/components/ListingContractQuestions/ListingCategory1.js
src/components/ListingContractQuestions/ListingCategory2.js
src/components/ListingContractQuestions/ListingCategory3.js
src/components/ListingContractQuestions/ListingCategory4.js
src/components/ListingContractQuestions/ListingCategory5.js
src/components/ListingContractQuestions/ListingCategory6.js
src/components/ListingContractQuestions/ListingCategory7.js
src/components/ListingContractQuestions/ListingCategory8.js
src/components/PurchaseAgreementDraftsIndividualDocs/PurchaseAgreementDraftsIndividualDocs.js
src/components/PurchaseAgreementQuestions/PurchaseCategory1.js
src/components/PurchaseAgreementQuestions/PurchaseCategory3.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js
src/components/PurchaseAgreementQuestions/PurchaseCategory5.js
src/components/PurchaseAgreementQuestions/PurchaseCategory6.js
src/components/PurchaseAgreementQuestions/PurchaseCategory7.js
src/components/PurchaseAgreementQuestions/PurchaseCategory8.js
src/components/PurchaseAgreementQuestions/PurchaseCategory9.js
src/components/Signature/PurchaseSignature.js
src/components/Signature/Signature.js
src/components/helpers/valueCheckerHelpers.js
src/redux/sagas/signSaga.js

I erased the autofills on the listing contract, I also cleaned up all the code as I worked on the logic of pages 1-9.

Double checking purchase logic

---

src/components/InfoPage/InfoPage.js
src/redux/sagas/pdfOffer.js

look over this and approve please

fixed errors on pdf one

---

src/redux/sagas/pdfOffer.js

added comments to page one of purchase

added comments

---

src/components/Signature/PurchaseSignature.js

added container to the purchaseSignature component

added container to purchaseSignature

---

src/components/Signature/PurchaseSignature.js
src/components/Signature/Signature.js

Hey ladies, i fixed the signature pages for listing and purchase. Also the confirm button for purchase to mirror listing.

fixed signature pages for listing and purchase

---

src/components/App/App.js
src/components/ListingContractQuestions/ListingCategory1.js
src/components/PurchaseAgreementQuestions/PurchaseCategory1.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js
src/components/PurchaseAgreementQuestions/PurchaseCategory5.js
src/components/PurchaseAgreementQuestions/PurchaseCategory7.js
src/components/PurchaseAgreementQuestions/PurchaseCategory8.js
src/components/PurchaseAgreementQuestions/PurchaseCategory9.js
src/components/helpers/valueCheckerHelpers.js
src/redux/sagas/fetchPurchaseAnswers.js

hey ladies, i pushed the changes to the checkbox logic for purchase categories. review and approve please.

fixed checkbox logic for purchase categories

---

package-lock.json
package.json
src/components/Signature/Signature.js

Need to run npm install to get react-responsive

feat: install react-responsive to handle orientation changes

---

server/pdfs/purchase_coords.js
server/routes/purchase_agreement.router.js
src/components/IndividualDrafts/IndividualDrafts.js
src/components/PurchaseAgreementQuestions/PurchaseCategory4.js

Reverts amran15/instant-offer#213
Ended up finding too many errors that kept on popping up as I continued to work...

Revert "finished first round of purchase coordinates"
